# Generated by Django 5.2.16 on 2026-08-06 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_id', models.CharField(max_length=64, unique=True)),
                ('state', models.CharField(choices=[('active', 'Active'), ('committed', 'Committed'), ('released', 'Released'), ('unknown', 'Unknown')], default='active', max_length=9)),
                ('expires_at', models.DateTimeField()),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_holds', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'expires_at'], name='idx_hold_state_expiry')],
            },
        ),
    ]
