# Generated by Django 5.2.16 on 2026-08-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_stockhold'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=48)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('dead', 'Dead')], default='pending', max_length=7)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(db_index=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'next_attempt_at'], name='idx_outbox_ready')],
            },
        ),
    ]
