# MetroDrip's staging image intentionally uses the same Python major/minor
# version locked by the handover so container and developer behavior match.
FROM python:3.14-slim AS runtime

# Python logs must reach the container runtime immediately, and generated byte
# code/cache files should not mutate the runtime filesystem unexpectedly.
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1

# A fixed identity makes ownership auditable on every host and prevents the
# web process from inheriting root privileges after the image is built.
ARG APP_UID=10001
ARG APP_GID=10001
RUN groupadd --gid "${APP_GID}" metrodrip \
    && useradd --uid "${APP_UID}" \
        --gid "${APP_GID}" \
        --create-home \
        --no-log-init \
        --shell /usr/sbin/nologin \
        metrodrip

WORKDIR /app

# Copying the dependency manifest first preserves Docker's dependency layer
# cache when only application code changes.
COPY requirements.txt ./
RUN python -m pip install -r requirements.txt

# Source stays root-owned and read-only to the unprivileged web identity. Only
# generated static output needs runtime write access for collectstatic.
COPY . .
RUN mkdir -p /app/staticfiles \
    && chown -R "${APP_UID}:${APP_GID}" /app/staticfiles \
    && chmod 0755 /app/deploy/entrypoint.sh

USER ${APP_UID}:${APP_GID}

# This port is exposed only to the Compose network; Caddy is the sole public
# ingress and terminates HTTPS before forwarding to Gunicorn.
EXPOSE 8000

ENTRYPOINT ["/app/deploy/entrypoint.sh"]

# One worker is deliberate: MetroDrip's v1 background scheduler is process-local,
# so multiple Gunicorn workers would duplicate scheduled jobs. Threads retain
# useful request concurrency until the scheduler is moved to a dedicated worker.
CMD ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "1", "--threads", "4", "--timeout", "60", "--access-logfile", "-", "--error-logfile", "-", "--capture-output"]
