# Generated by Django 5.2.16 on 2026-07-18 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('committed', 'Committed'), ('released', 'Released'), ('expired', 'Expired')], default='active', max_length=9)),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='orders.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='catalog.productvariant')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'expires_at'], name='idx_res_status_expiry')],
                'constraints': [models.CheckConstraint(condition=models.Q(('qty__gte', 1)), name='chk_reservation_qty_min1')],
            },
        ),
    ]
