# Generated by Django 5.2.16 on 2026-08-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('key_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('status_code', models.PositiveSmallIntegerField(default=0)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'idempotency record',
                'verbose_name_plural': 'idempotency records',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='checkout_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
