"""Catalog domain (§4, FR-1): Product → ProductVariant, 3-axis variants.

Every Size × Color × Fit combination is exactly one SKU with its own stock
(FR-1); stock itself lives in apps.inventory, keeping catalog free of any
quantity math.
"""

from django.core.exceptions import ValidationError
from django.db import models


class Category(models.Model):
    """Two-level taxonomy: main categories with optional audience children.

    `name` is deliberately NOT globally unique — "Men" must be able to exist
    under every main category. Global identity lives on `slug`, which is why
    child slugs are parent-prefixed (`hoodies-men`).
    """

    #: Roots plus one level of children. Enforced in `clean()`; see the note on
    #: `Meta.constraints` for why the database cannot check this itself.
    MAX_DEPTH = 2

    name = models.CharField(max_length=120)
    slug = models.SlugField(max_length=140, unique=True)
    parent = models.ForeignKey(
        "self",
        null=True,
        blank=True,
        on_delete=models.PROTECT,
        related_name="children",
        help_text="Leave empty for a main category.",
    )

    class Meta:
        verbose_name_plural = "categories"
        ordering = ["name"]
        constraints = [
            # Sibling names must be distinct. This covers children only: for
            # roots `parent_id` is NULL, and MySQL treats every NULL as distinct
            # in a unique index, so root names are enforced in `clean()`.
            # A conditional constraint is not an option — MySQL has no partial
            # indexes, so Django would silently skip it (models.W036).
            models.UniqueConstraint(fields=["parent", "name"], name="uniq_category_sibling_name"),
            # Self-parenting and depth are both validation-only. Depth needs a
            # join, which a CHECK cannot do; and MySQL rejects a CHECK that
            # references an AUTO_INCREMENT column outright (error 3818), so even
            # `parent_id <> id` is unavailable here.
        ]

    def __str__(self):
        return self.name

    @property
    def is_root(self):
        return self.parent_id is None

    @property
    def hierarchy_label(self):
        """Human-readable path, e.g. "Hoodies → Men"."""
        return self.name if self.is_root else f"{self.parent.name} → {self.name}"

    def clean(self):
        """Reject self-parenting, third-level nesting, and duplicate siblings.

        Django calls this from ModelForm validation, so the admin is covered.
        It is not invoked by bare `Model.save()`; callers that bypass forms are
        expected to build valid data (the seed commands use fixed taxonomies).
        """
        errors = {}

        if self.parent_id is not None:
            if self.pk is not None and self.parent_id == self.pk:
                errors["parent"] = "A category cannot be its own parent."
            elif self.parent.parent_id is not None:
                errors["parent"] = (
                    f"Categories may not nest more than {self.MAX_DEPTH} levels deep. "
                    f"'{self.parent}' is already a subcategory."
                )
            elif self.pk is not None and self.children.exists():
                errors["parent"] = (
                    "This category has subcategories, so it cannot become a subcategory itself."
                )

        if self.name:
            siblings = Category.objects.filter(parent_id=self.parent_id, name=self.name)
            if self.pk is not None:
                siblings = siblings.exclude(pk=self.pk)
            if siblings.exists():
                scope = f"under '{self.parent}'" if self.parent_id else "as a main category"
                errors["name"] = f"A category named '{self.name}' already exists {scope}."

        if errors:
            raise ValidationError(errors)


class Size(models.TextChoices):
    XS = "XS", "Extra Small"
    S = "S", "Small"
    M = "M", "Medium"
    L = "L", "Large"
    XL = "XL", "Extra Large"
    XXL = "XXL", "2X Large"


class Fit(models.TextChoices):
    SLIM = "slim", "Slim"
    REGULAR = "regular", "Regular"
    OVERSIZED = "oversized", "Oversized"


class Product(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=220, unique=True)
    description = models.TextField(blank=True)
    # FK per §4's key-field table (category_id); the diagram's *──* was resolved
    # to the simpler single-category design — see DECISIONS.md.
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name="products")
    # Hard Invariant 2: money is integer centavos, formatted only at display time.
    base_price = models.PositiveIntegerField(help_text="Price in centavos (integer).")
    # Ordered list of CDN image URLs; object storage per §2, so no ImageField/disk.
    images = models.JSONField(default=list, blank=True)
    is_active = models.BooleanField(default=True)
    # Marks rows generated by `seed_mock_catalog`. Purely an audit/bookkeeping
    # flag: `is_active` remains the sole storefront visibility boundary, so a
    # placeholder is as visible as any hand-authored product.
    is_mock = models.BooleanField(
        default=False,
        db_index=True,
        help_text="Generated placeholder data rather than a real product.",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return self.name


class ProductVariant(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="variants")
    sku = models.CharField(max_length=64, unique=True)
    size = models.CharField(max_length=4, choices=Size.choices)
    color = models.CharField(max_length=40)
    fit = models.CharField(max_length=10, choices=Fit.choices)
    # NULL = variant sells at product.base_price; set only for surcharge sizes etc.
    price_override = models.PositiveIntegerField(null=True, blank=True)

    class Meta:
        constraints = [
            # One SKU per axis combination (§1: Size × Color × Fit = one SKU).
            models.UniqueConstraint(
                fields=["product", "size", "color", "fit"], name="uniq_variant_axes"
            ),
        ]

    def __str__(self):
        return self.sku

    @property
    def price(self):
        """Effective unit price in centavos — the only place override logic lives."""
        return self.price_override if self.price_override is not None else self.product.base_price
