# Generated by Django 5.2.16 on 2026-07-18 14:54

import django.db.models.deletion
from django.db import migrations, models


def configure_mysql_defaults(apps, schema_editor):
    """Set and verify the locked engine/charset before application tables exist."""
    connection = schema_editor.connection
    if connection.vendor != "mysql":
        raise RuntimeError("MetroDrip migrations require MySQL 8.")

    # The configured name is trusted deployment configuration, and quote_name
    # turns it into a safe MySQL identifier rather than interpolated SQL data.
    database_name = connection.settings_dict["NAME"]
    quoted_database = connection.ops.quote_name(database_name)

    with connection.cursor() as cursor:
        # ALTER DATABASE fixes the default used by every table created later in
        # this migration graph; the session setting independently pins InnoDB.
        cursor.execute(
            f"ALTER DATABASE {quoted_database} "
            "CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci"
        )
        cursor.execute("SET SESSION default_storage_engine = InnoDB")

        # Django creates its migration-recorder table before the first operation,
        # so normalize that one pre-existing table explicitly as well.
        cursor.execute(
            "ALTER TABLE django_migrations ENGINE=InnoDB, "
            "CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci"
        )

        # Fail before domain tables are created if the server rejected or
        # normalized either locked database default unexpectedly.
        cursor.execute(
            """
            SELECT default_character_set_name, default_collation_name
            FROM information_schema.schemata
            WHERE schema_name = DATABASE()
            """
        )
        database_defaults = cursor.fetchone()
        cursor.execute("SELECT @@SESSION.default_storage_engine")
        storage_engine = cursor.fetchone()[0]

    expected_defaults = ("utf8mb4", "utf8mb4_0900_ai_ci")
    if database_defaults != expected_defaults or storage_engine.lower() != "innodb":
        raise RuntimeError("MySQL did not apply the required InnoDB/utf8mb4 defaults.")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.RunPython(configure_mysql_defaults, migrations.RunPython.noop),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.PositiveIntegerField(help_text='Price in centavos (integer).')),
                ('images', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2X Large')], max_length=4)),
                ('color', models.CharField(max_length=40)),
                ('fit', models.CharField(choices=[('slim', 'Slim'), ('regular', 'Regular'), ('oversized', 'Oversized')], max_length=10)),
                ('price_override', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'size', 'color', 'fit'), name='uniq_variant_axes')],
            },
        ),
    ]
