# Generated by Django 5.2.16 on 2026-07-28 07:08
"""Introduce the two-level category taxonomy (Epic A).

Adds `Category.parent`, drops the global uniqueness of `Category.name` so that
"Men" can exist under every main category, and back-fills audience children for
whatever main categories a database already holds.

The back-fill is a no-op on a fresh database, which has no categories at migrate
time. `seed_mock_catalog` therefore re-ensures the same children itself, so a
freshly migrated-then-seeded database ends up identical to a migrated existing
one.
"""

import django.db.models.deletion
from django.db import migrations, models

# Kept literal rather than imported from apps.catalog: a migration must keep
# describing the change it originally made even if the application constant
# later changes.
AUDIENCES = (("Men", "men"), ("Women", "women"))


def create_audience_children(apps, schema_editor):
    """Give every existing main category a Men and a Women subcategory."""
    Category = apps.get_model("catalog", "Category")

    for root in Category.objects.filter(parent__isnull=True).order_by("slug"):
        for name, slug_suffix in AUDIENCES:
            Category.objects.get_or_create(
                slug=f"{root.slug}-{slug_suffix}",
                defaults={"name": name, "parent": root},
            )


def remove_audience_children(apps, schema_editor):
    """Drop generated children that no product references.

    Children holding products are left in place: `Product.category` is
    PROTECTed, and silently reassigning or deleting catalogue rows to make a
    migration reversible would lose real data.
    """
    Category = apps.get_model("catalog", "Category")

    slugs = [
        f"{slug}-{suffix}"
        for slug in Category.objects.filter(parent__isnull=True).values_list("slug", flat=True)
        for _, suffix in AUDIENCES
    ]
    Category.objects.filter(
        slug__in=slugs, parent__isnull=False, products__isnull=True
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_enforce_mysql_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leave empty for a main category.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_mock',
            field=models.BooleanField(db_index=True, default=False, help_text='Generated placeholder data rather than a real product.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='uniq_category_sibling_name'),
        ),
        migrations.RunPython(create_audience_children, remove_audience_children),
    ]
